version: "3.9"

x-defaults: &x-defaults
  image: local
  build: .
  env_file:
    - .env
  restart: always
  stdin_open: true
  tty: true
  dns:
    - 8.8.8.8
    - 8.8.4.4
  depends_on:
    - postgres
    - rabbitmq
    - memcached


services:
  backend:
#    command: python ./app/manage.py runserver 0.0.0.0:8000
    container_name: backend
    ports:
      - "8000:8000"
      - "8001:8001" # debug
    volumes:
      - "./:/project/code"
    <<: *x-defaults

  celery:
    command: celery -A settings worker -l info --autoscale=0,10
    container_name: celery
    <<: *x-defaults

  celerybeat:
    command: celery -A settings beat -l info
    container_name: celerybeat
    <<: *x-defaults

  memcached:
    image: memcached:1.6.21-alpine
    container_name: memcached
#    ports:
#      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.12.4-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
#      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15.4-alpine
    container_name: postgres
    env_file:
      - .env
#    ports:
#      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"

volumes:
  db_data: {}
