version: "3.11"

services:
  backend:
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - "./:/project/code"
    image: local
    build: .
    env_file:
      - .env
    restart: always
    stdin_open: true
    tty: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - postgres

  postgres:
    image: postgres:15.4-alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

volumes:
  db_data: {}
